version: '3'
services:
  Host:
    image: alpine
    restart: unless-stopped
    container_name: host-mflores
  
  Router:
    image: debian
    restart: unless-stopped
    container_name: router-mflores
