# Use the latest version of the Alpine base image
FROM alpine:latest

# Install the latest version of busybox
RUN apk add --no-cache busybox

# Set the default command to print "HAHAHAH"
CMD echo HAHAHAH
