#!/bin/sh
# !!! RUN COMMAND INSIDE DOCKER CONTAINER

# Assign ip address on the eth0 interface
ip address add 10.1.1.1/24 dev eth0

# Add new network link with the name vxlan10 of type vxlan
# with an id of 10
# eth0 is the physicl network that will carry the traffic
# local ip is the source for packets
# remote ip is the destination
# port is the default port for vxlan
ip link add name vxlan10 type vxlan id 10 dev eth0 local 10.1.1.1 remote 10.1.1.2 dstport 4789
ip link set dev vxlan10 up

# Add bridge
# Acts like a virtual switch
# allows to connect multiple network interfaces together
# so they can communicate at the data link layer (Layer 2).
ip link add br0 type bridge
ip link set dev br0 up
ip link show br0

# Add eth1 and vxlan10 interfaces to br0:
brctl addif br0 eth1
brctl addif br0 vxlan10

#Check that eth1 and vxlan10 interfaces is part of bridge br0
ip link show eth1
ip link show vxlan10

# exec /bin/sh
/usr/lib/frr/docker-start

